export const content = {
  en: {
    header: {
      company: "Visernic Limited",
      tagline: "Professional Web Solutions",
      status: "Development Active",
    },
    hero: {
      badge: "Something Amazing is Coming",
      title: "Coming Soon",
      subtitle:
        "We are currently crafting an exceptional digital experience that will completely revolutionize how you interact with our professional services.",
      description: "Get ready for a new era of innovation, operational excellence, and cutting-edge technology designed to scale your business.",
    },
    timer: {
      title: "Launch Countdown",
      subtitle: "Every second brings us closer to unveiling something extraordinary for you",
      hours: "Hours",
      minutes: "Minutes",
      seconds: "Seconds",
    },
    progress: {
      title: "Development Progress",
      subtitle: "Our website development phase is currently in active progress",
      overall: "Overall Completion",
      features: "Core Features",
      uptime: "System Uptime",
    },
    features: {
      title: "What's Coming",
      subtitle: "We have exciting features ahead",
      items: [
        { text: "Modern UI/UX Design System", completed: true },
        { text: "Fully Mobile Responsive Layouts", completed: true },
        { text: "Advanced Security Features", completed: false },
        { text: "High Performance Optimization", completed: false },
      ],
    },
    company: {
      poweredBy: "Powered by",
      title: "Visernic Limited",
      description: "Visernic Limited is leading the global digital transformation with innovative custom web solutions, software development, and cutting-edge technology services tailored for modern businesses.",
      team: {
        title: "Expert Team",
        desc: "Certified professional developers",
      },
      quality: {
        title: "Quality Assured",
        desc: "International premium standards",
      },
      delivery: {
        title: "Fast Delivery",
        desc: "Guaranteed on-time completion",
      },
      cta: "Visit Our Main Website",
    },
    contact: {
      title: "Have any questions?",
      subtitle: "Feel free to get in touch with our support team",
      phone: {
        label: "Call us",
        value: "+447366493955",
      },
      email: {
        label: "Email us",
        value: "Click to reveal email",
      },
      office: {
        label: "Visit office",
        value: "Nazipur, Naogaon, 6540",
      },
      contactUs: "Contact Support",
    },
    footer: {
      copyright: "© 2024 Visernic Limited. All rights reserved globally.",
      tagline1: "Professional Web Development Services",
      tagline2: "Commitment to Innovation & Excellence",
    },
    dailyUpdates: [
      "🚀 Backend server architecture development in progress",
      "🎨 User Interface and Experience design refinements",
      "⚡ High-performance code optimization underway",
      "🔧 Secure database architecture implementation",
      "📱 Mobile responsiveness and compatibility testing",
      "🛡️ Advanced security protocol integration",
      "🌟 New functionality and features being developed",
      "🔍 Comprehensive quality assurance testing",
      "📊 Real-time analytics dashboard creation",
      "🎯 User experience flow improvements",
      "💡 Future innovation features planning",
      "🔄 System integration and API progress",
      "📈 Performance metrics and speed optimization",
      "🎪 Interactive frontend elements development",
      "🌐 Multi-language localization support enhancement",
    ],
    todayUpdate: "Today's Status Update:",
  },
  bn: {
    header: {
      company: "ভিজারনিক লিমিটেড",
      tagline: "পেশাদার ওয়েব সমাধান",
      status: "ডেভেলপমেন্ট চলমান",
    },
    hero: {
      badge: "অসাধারণ কিছু আসছে",
      title: "শীঘ্রই আসছে",
      subtitle: "আমরা একটি ব্যতিক্রমী ডিজিটাল অভিজ্ঞতা তৈরি করছি যা আমাদের সেবার সাথে আপনার মিথস্ক্রিয়ায় সম্পূর্ণ বিপ্লব আনবে।",
      description: "আপনার ব্যবসার উন্নতির জন্য উদ্ভাবন, উৎকর্ষতা এবং অত্যাধুনিক প্রযুক্তির নতুন যুগের জন্য প্রস্তুত হন।",
    },
    timer: {
      title: "লঞ্চ কাউন্টডাউন",
      subtitle: "প্রতিটি সেকেন্ড আমাদের অসাধারণ কিছু উন্মোচনের দিকে নিয়ে যাচ্ছে",
      hours: "ঘন্টা",
      minutes: "মিনিট",
      seconds: "সেকেন্ড",
    },
    progress: {
      title: "ডেভেলপমেন্ট অগ্রগতি",
      subtitle: "ওয়েবসাইট ডেভেলপমেন্ট কাজ বর্তমানে পুরোদমে চলছে",
      overall: "সামগ্রিক অগ্রগতি",
      features: "কোর ফিচার",
      uptime: "সিস্টেম আপটাইম",
    },
    features: {
      title: "যা আসছে",
      subtitle: "সামনে রোমাঞ্চকর ফিচারসমূহ রয়েছে",
      items: [
        { text: "আধুনিক UI/UX ডিজাইন সিস্টেম", completed: true },
        { text: "সম্পূর্ণ মোবাইল রেসপন্সিভ লেআউট", completed: true },
        { text: "উন্নত নিরাপত্তা ফিচারসমূহ", completed: false },
        { text: "উচ্চ পারফরম্যান্স অপটিমাইজেশন", completed: false },
      ],
    },
    company: {
      poweredBy: "চালিত",
      title: "ভিজারনিক লিমিটেড",
      description: "ভিজারনিক লিমিটেড আধুনিক ব্যবসার জন্য উদ্ভাবনী কাস্টম ওয়েব সমাধান এবং অত্যাধুনিক প্রযুক্তির সাথে ডিজিটাল রূপান্তরে নেতৃত্ব দিচ্ছে।",
      team: {
        title: "বিশেষজ্ঞ দল",
        desc: "সার্টিফাইড পেশাদার ডেভেলপার",
      },
      quality: {
        title: "মান নিশ্চিত",
        desc: "আন্তর্জাতিক প্রিমিয়াম মানদণ্ড",
      },
      delivery: {
        title: "দ্রুত ডেলিভারি",
        desc: "নির্ধারিত সময়ে সম্পন্ন করার নিশ্চয়তা",
      },
      cta: "আমাদের ওয়েবসাইট দেখুন",
    },
    contact: {
      title: "কোন প্রশ্ন আছে?",
      subtitle: "আমাদের সাপোর্ট টিমের সাথে যোগাযোগ করুন",
      phone: {
        label: "কল করুন",
        value: "+৪৪৭৩৬৬৪৯৩৯৫৫",
      },
      email: {
        label: "ইমেইল করুন",
        value: "ইমেইল দেখতে ক্লিক করুন",
      },
      office: {
        label: "অফিস দেখুন",
        value: "নজিপুর, নওগাঁ, ৬৫৪০",
      },
      contactUs: "যোগাযোগ করুন",
    },
    footer: {
      copyright: "© ২০২৪ ভিজারনিক লিমিটেড। সকল অধিকার বিশ্বব্যাপী সংরক্ষিত।",
      tagline1: "পেশাদার ওয়েব ডেভেলপমেন্ট সার্ভিস",
      tagline2: "উদ্ভাবন ও উৎকর্ষতার প্রতিশ্রুতি",
    },
    dailyUpdates: [
      "🚀 ব্যাকএন্ড সার্ভার আর্কিটেকচার ডেভেলপমেন্ট চলমান",
      "🎨 UI/UX ডিজাইন এবং অভিজ্ঞতার উন্নতি চলছে",
      "⚡ হাই-পারফরম্যান্স কোড অপটিমাইজেশন চলমান",
      "🔧 সুরক্ষিত ডেটাবেস আর্কিটেকচার বাস্তবায়ন",
      "📱 মোবাইল রেসপন্সিভনেস এবং কম্প্যাটিবিলিটি টেস্টিং",
      "🛡️ অ্যাডভান্সড সিকিউরিটি প্রোটোকল ইন্টিগ্রেশন",
      "🌟 নতুন ফাংশনালিটি এবং ফিচার ডেভেলপমেন্ট",
      "🔍 বিস্তারিত কোয়ালিটি অ্যাসিউরেন্স টেস্টিং",
      "📊 রিয়েল-টাইম অ্যানালিটিক্স ড্যাশবোর্ড তৈরি",
      "🎯 ইউজার এক্সপেরিয়েন্স ফ্লো উন্নতি",
      "💡 ফিউচার ইনোভেশন ফিচার পরিকল্পনা",
      "🔄 সিস্টেম ইন্টিগ্রেশন এবং API অগ্রগতি",
      "📈 পারফরম্যান্স মেট্রিক্স এবং স্পিড অপটিমাইজেশন",
      "🎪 ইন্টারঅ্যাক্টিভ ফ্রন্টএন্ড এলিমেন্ট ডেভেলপমেন্ট",
      "🌐 মাল্টি-ল্যাঙ্গুয়েজ লোকালাইজেশন সাপোর্ট উন্নতি",
    ],
    todayUpdate: "আজকের স্ট্যাটাস আপডেট:",
  },
}
